Failure # 1 (occurred at 2023-02-18_14-50-22)
Traceback (most recent call last):
  File "/home/matous/miniconda3/envs/amg-env/lib/python3.9/site-packages/ray/tune/execution/ray_trial_executor.py", line 996, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/home/matous/miniconda3/envs/amg-env/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/matous/miniconda3/envs/amg-env/lib/python3.9/site-packages/ray/_private/worker.py", line 2282, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: DQN
	actor_id: 85225d8dbb58e8df3742674101000000
	pid: 47743
	namespace: 652693d2-68c8-4a31-bbc9-9f8df96992dd
	ip: 192.168.0.104
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

